# Generated by Django 6.0.7 on 2026-08-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('data_ingresso', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
